services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JosefGlatz\Bureaucratic\:
    resource: '../Classes/*'

  JosefGlatz\Bureaucratic\Services\EmailService:
    public: true

